version: '3.8'

services:
  app:
    build: .
    ports:
      - '${PORT}:${PORT}'
    environment:
      - DB=${DB}
      - PORT=${PORT}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
